### ISSUE TITLE
Checkpoint name

### ISSUE THREAD

**Issue by Kimsure** [swagger-coder/ASDA#6]
Why do you name the checkpoint file with a .tar suffix when saving it? It confused me the checkpoint needs to be extracted before it can be loaded. I suggest removing the .tar suffix when saving the file at [checkpoint.py](https://github.com/swagger-coder/ASDA/blob/main/utils/checkpoint.py#L11-L12) to avoid misunderstandings.

**Comment by wqqqqq0720** [comment]
hi,Did you know that there are two modules in the modul.py, KLM and KAM, and do you know what they are for?

**Comment by wqqqqq0720** [comment]
> Why do you name the checkpoint file with a .tar suffix when saving it? It confused me the checkpoint needs to be extracted before it can be loaded. I suggest removing the .tar suffix when saving the file at [checkpoint.py](https://github.com/swagger-coder/ASDA/blob/main/utils/checkpoint.py#L11-L12) to avoid misunderstandings.
hi,Did you know that there are two modules in the modul.py, KLM and KAM, and do you know what they are for?

**Comment by wqqqqq0720** [comment]
> Why do you name the checkpoint file with a .tar suffix when saving it? It confused me the checkpoint needs to be extracted before it can be loaded. I suggest removing the .tar suffix when saving the file at [checkpoint.py](https://github.com/swagger-coder/ASDA/blob/main/utils/checkpoint.py#L11-L12) to avoid misunderstandings.

.tar suffix does not affect the model being called

**Comment by Kimsure** [comment]
Yep, just for a reminder
